name: 'James || Chapa, PLLC'
favicon: null
layout_spectrum: 0.12468039174564183
typography_spectrum: 0.19748554285615683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5851455214433372
  lightness: 0.20142031111754477
  saturation: 0.6917446234729141
  rhythmicContrast: 0.16265165572986007
purpose: []
